server:
  port: 1251
  context-path: /task-job-api
spring:
  datasource:
    url: jdbc:mysql://119.37.194.4:11161/ie-inspection?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: '!QQ1234567890-=q'
    driver-class-name: com.mysql.jdbc.Driver